# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('dob', models.CharField(max_length=30, verbose_name='date of birth')),
                ('zip', models.CharField(max_length=10, verbose_name='zip code')),
            ],
            options={
                'ordering': ['-created', 'last_name', 'first_name'],
                'verbose_name_plural': 'people',
            },
        ),
    ]
